# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: demoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
        version: v1
    spec:
      containers:
      - name: demoapp
        image: europe-west3-docker.pkg.dev/YOUR_PROJECT/java/jmx-demo:latest
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 10
          failureThreshold: 3
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /actuator/health
            port: http
          failureThreshold: 30
          periodSeconds: 10
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 1
            memory: 512Mi
        ports:
          - name: http
            containerPort: 8080
          - name: metrics
            containerPort: 12345
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp
  namespace: apps
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  - port: 12345
    targetPort: 12345
    name: metrics
  selector:
    app: demoapp
  type: ClusterIP
